# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parature', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketdetails',
            options={'managed': False, 'verbose_name': 'Ticket Details', 'verbose_name_plural': 'Tickets Details'},
        ),
        migrations.AlterModelOptions(
            name='tickethistory',
            options={'managed': False, 'verbose_name': 'Ticket History Item'},
        ),
    ]
